default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: menuxenterprise_development
  username: dhiomenuxenterprise
  password: hauntmex3

test:
  <<: *default
  database: menuxenterprise_test
  username: dhiomenuxenterprise
  password: hauntmex3

production:
  <<: *default
  database: menuxenterprise_production
  username: dhiomenuxenterprise
  password: <%= ENV["MENUXENTERPRISE_DATABASE_PASSWORD"] %>
